# wrangler.toml
name = "1"
main = "worker/src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "public"

[observability]
enabled = true

[triggers]
crons = ["*/30 * * * *"]

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "3eaee00ba53e4ee7ada81f85e5651f3f"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "9a155db1bf8b49d1aed24a385d3508c0"
